In [113]:
# Essential Imports
import zipfile
import pandas as pd
import seaborn as sns
import sklearn as skt
import matplotlib.pyplot as plt
import datetime
import numpy as np
from itertools import combinations
from collections import defaultdict
from datetime import datetime
import pickle
import warnings
warnings.simplefilter("ignore")
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder

In [176]:
data = pd.read_csv('/Users/ashvtol/Downloads/weather.txt', delim_whitespace=True, header='infer')

In [177]:
data

,USAF,WBAN,YR--MODAHRMN,DIR,SPD,GUS,CLG,SKC,L,M,...,SLP,ALT,STP,MAX,MIN,PCP01,PCP06,PCP24,PCPXX,SD
0,725050,4781,201501010056,230,5,***,722,SCT,*,*,...,1023.5,30.22,1019.7,***,***,0.00,*****,*****,*****,**
1,725050,4781,201501010156,250,5,***,722,CLR,*,*,...,1023.1,30.21,1019.4,***,***,0.00,*****,*****,*****,**
2,725050,4781,201501010256,250,7,***,722,CLR,*,*,...,1022.4,30.19,1018.7,***,***,0.00,*****,*****,*****,**
3,725050,4781,201501010356,260,3,***,722,CLR,*,*,...,1021.8,30.17,1018.0,***,***,0.00,*****,*****,*****,**
4,725050,4781,201501010456,270,5,***,722,CLR,*,*,...,1021.3,30.16,1017.7,32,22,0.00,*****,*****,*****,**
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53960,725050,4781,201911230656,290,9,***,722,CLR,*,*,...,1015.0,29.97,******,***,***,*****,*****,*****,*****,**
53961,725050,4781,201911231256,260,8,***,722,***,*,*,...,1017.9,30.06,1014.3,***,***,*****,*****,*****,*****,**
53962,725050,4781,201911231356,270,10,***,722,***,*,*,...,1017.4,30.04,1013.7,***,***,*****,*****,*****,*****,**
53963,725050,4781,201911231456,280,7,***,722,***,*,*,...,1017.4,30.04,1013.7,***,***,*****,*****,*****,*****,**
53964,725050,4781,201911231556,990,3,***,250,***,*,*,...,1016.4,30.01,1012.6,***,***,*****,*****,*****,*****,**

In [178]:
data = data[['YR--MODAHRMN','TEMP','PCP24','SD']]

In [179]:
data.head(5)

   YR--MODAHRMN TEMP  PCP24  SD
0  201501010056   26  *****  **
1  201501010156   25  *****  **
2  201501010256   25  *****  **
3  201501010356   25  *****  **
4  201501010456   24  *****  **

In [180]:
data.loc[(data['PCP24'] == '*****'), 'PCP24'] = 0

In [181]:
data.loc[(data['SD'] == '**'), 'SD'] = 0

In [182]:
data.loc[(data['TEMP'] == '****'), 'TEMP'] = 0

In [183]:
d2 = data

In [184]:
d2.columns = ['Date', 'Temp', 'PCP24', 'sd']

In [185]:
d2['Date'] = d2['Date'].astype('str')

In [186]:
def convert(s):
    date = datetime.strptime(s,"%Y%m%d%H%M")
    return str(str(date.month )+ "/" + str(date.day) + "/" + str(date.year))

In [187]:
d2['Date'] = d2['Date'].apply(lambda x: convert(x))

ValueError: invalid literal for int() with base 10: '0.00'

ValueError: invalid literal for int() with base 10: '0.00'

In [188]:
d2['Temp'] = pd.to_numeric(d2['Temp'], errors = 'coerce')

In [189]:
d2['PCP24'] = pd.to_numeric(d2['PCP24'], errors = 'coerce')

In [190]:
d2['sd'] = pd.to_numeric(d2['sd'], errors = 'coerce')

In [191]:
d2['Date'] = d2['Date'].astype('str')

In [192]:
d3  = d2.groupby(['Date'])['Temp','PCP24','sd'].mean()

In [193]:
d4 = pd.DataFrame(d3)

In [195]:
d4

               Temp     PCP24    sd
Date
1/1/2015  28.240000  0.000000  0.00
1/1/2016  39.160000  0.008800  0.00
1/1/2017  41.480000  0.000417  0.00
1/1/2018  10.640000  0.000000  0.16
1/1/2019  50.097561  0.067561  0.00
...             ...       ...   ...
9/9/2015  76.125000  0.000000  0.00
9/9/2016  76.888889  0.000000  0.00
9/9/2017  59.400000  0.000000  0.00
9/9/2018  59.240000  0.003478  0.00
9/9/2019  66.640000  0.000000  0.00

[1788 rows x 3 columns]

In [194]:
d4.to_csv('/Users/ashvtol/Documents/dsfProjectData/weatherData.csv')